@startuml
interface discount.FreeDiscountable {
+ {abstract}int calcFreeDiscountPieces(int)
}

class logic.ShopUtil {
+ {static} int calculateFreeDiscountPieces(int,int,int)
+ {static} int calculateDiscountUsingPercent(int,double)
}

class products.BaseProduct {
# String productName
# int price
+ <<Create>> BaseProduct(String,int)
+ String getProductName()
+ void setProductName(String)
+ int getPrice()
+ void setPrice(int)
+ int calculateDiscount(int)
+ String toString()
}


interface discount.Sellable {
+ {abstract}int calculateDiscount(int)
+ {abstract}void setProductName(String)
+ {abstract}String getProductName()
+ {abstract}void setPrice(int)
+ {abstract}int getPrice()
}

class products.PercentDiscountProduct {
- double percent
+ <<Create>> PercentDiscountProduct(String,int,double)
+ double getPercent()
+ void setPercent(double)
+ int calcDiscountPerPiece()
+ int calculateDiscount(int)
+ String toString()
}


class products.FreeDiscountProduct {
- int promoQuantity
- int freeQuantity
+ <<Create>> FreeDiscountProduct(String,int,int,int)
+ int getPromoQuantity()
+ void setPromoQuantity(int)
+ int getFreeQuantity()
+ void setFreeQuantity(int)
+ int calcFreeDiscountPieces(int)
+ int calculateDiscount(int)
+ String toString()
}


class app.Main {
~ {static} Bill bill
~ {static} ArrayList<Sellable> shop
~ {static} Scanner sc
+ {static} void main(String[])
+ {static} void showItems()
+ {static} boolean addItem()
+ {static} boolean removeItem()
+ {static} boolean addItemToBill()
+ {static} boolean removeItemFromBill()
}


interface discount.PercentDiscountable {
+ {abstract}int calcDiscountPerPiece()
}

class logic.Bill {
+ ArrayList<BillItem> itemsInBill
+ <<Create>> Bill()
+ void printAllItemsInBill()
+ int getTotalBillPrice(boolean)
}


class logic.BillItem {
~ Sellable itemInLine
~ int quantity
+ <<Create>> BillItem(Sellable,int)
+ Sellable getItemInLine()
+ void setItemInLine(Sellable)
+ int getQuantity()
+ void setQuantity(int)
+ int getPrice(boolean)
+ String toString()
}




discount.Sellable <|-- discount.FreeDiscountable
discount.Sellable <|.. products.BaseProduct
discount.Sellable <|.. products.PercentDiscountProduct
discount.PercentDiscountable <|.. products.PercentDiscountProduct
products.BaseProduct <|-- products.PercentDiscountProduct
discount.Sellable <|.. products.FreeDiscountProduct
discount.FreeDiscountable <|.. products.FreeDiscountProduct
products.BaseProduct <|-- products.FreeDiscountProduct
discount.Sellable <|-- discount.PercentDiscountable
@enduml