@startuml
class logic.Item {
- String name
- int pricePerPiece
+ <<Create>> Item(String,int)
+ String getName()
+ void setName(String)
+ int getPricePerPiece()
+ void setPricePerPiece(int)
}


class logic.OrderItem {
- Item item
- int itemAmount
+ <<Create>> OrderItem(Item,int)
+ void increaseItemAmount(int)
+ int calculateTotalPrice()
+ Item getItem()
+ void setItem(Item)
+ int getItemAmount()
+ void setItemAmount(int)
}


class application.CPShop {
- {static} ArrayList<Item> itemList
- {static} ArrayList<Order> orderList
- {static} boolean isEnd
- {static} Scanner kb
+ {static} void main(String[])
+ {static} void addItemToOrder(Order,int,int)
+ {static} boolean addNewItem(String,int)
+ {static} boolean isItemExisted(String)
- {static} void handleAddItem()
- {static} void handleCreateNewOrder()
- {static} void showAllItems()
- {static} void showAllOrder()
+ {static} ArrayList<Order> getOrderList()
+ {static} void addBlankOrder()
+ {static} void initializeData()
}


class logic.Order {
- ArrayList<OrderItem> orderItemList
- {static} int totalOrderCount
- int orderNumber
+ <<Create>> Order()
+ OrderItem addItem(Item,int)
+ int calculateOrderTotalPrice()
+ {static} int getTotalOrderCount()
+ {static} void resetTotalOrderCount()
+ int getOrderNumber()
+ ArrayList<OrderItem> getOrderItemList()
+ void setOrderItemList(ArrayList<OrderItem>)
+ {static} void setTotalOrderCount(int)
+ void setOrderNumber(int)
}


@enduml